name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Tests Python
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter-app

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: python -m pip install -r requirements.txt

      - name: Lancer les tests
        run: pytest -v
